### ISSUE TITLE
Unable to execute tests for svelte files that contain scss in the style tag

### ISSUE THREAD

**Issue by JordanKlaers** [bahmutov/cypress-svelte-unit-test#45]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?
I believe this is a bug

If this is a bug report, please provide as much info as possible

- version: ^1.5.0
- platform:
- expected behavior: I expect the tests to run when a svelte file contains scss in the style tag
- actual behavior: I get an error that the sccs syntax is not supported

I have copied my weback config into the plugins/index.js file. My webpack config has been set up to allow for the use of scss in the style tags in svelte files. 

I have a few different errors depending on how I try to solve this. If I remove the hotreload and style function under options for the svelte loader and remove the require for sass, I get an error regarding the scss syntax in the svelte file when the test runs.

if I keep everything, I get an error:
`Error: A dynamic link library (DLL) initialization routine failed.
` that comes from the require of the node-sass.

requiring the mini extract text plugin does not cause an issue. 

The project does run and process the scss correctly in localhost, just not when running the test.
below is my webpack config.
`     

     const MiniCssExtractPlugin = require('mini-css-extract-plugin');
     const mode = process.env.NODE_ENV || 'development';
     const prod = mode === 'production';
     const sass = require('node-sass');
`
`		

	module.exports = {
		entry: {
			bundle: ['./src/main.js']
		},
		resolve: {
			// see below for an explanation
			mainFields: ['svelte', 'browser', 'module', 'main'],
			extensions: ['.mjs', '.js', '.svelte']
		},
		output: {
			path: __dirname + '/public',
			filename: '[name].js',
			chunkFilename: '[name].[id].js'
		},
		module: {
			rules: [
				{
					test: /\.svelte$/,
					exclude: /node_modules/,
					use: {
						loader: 'svelte-loader',
						options: {
							emitCss: true,
							hotReload: true,
							style: ({ content, attributes }) => {
								if (attributes.type !== 'text/scss') return;

								return new Promise((fulfil, reject) => {
									sass.render({
										data: content,
										includePaths: ['src'],
										sourceMap: true,
										outFile: 'x' // this is necessary, but is ignored
									}, (err, result) => {
										if (err) return reject(err);

										fulfil({
											code: result.css.toString(),
											map: result.map.toString()
										});
									});
								});
							}
						}
					}
				},
				{
					test: /\.scss$/,
					use: [
						"style-loader", // creates style nodes from JS strings
						"css-loader", // translates CSS into CommonJS
						"sass-loader" // compiles Sass to CSS
					]
				},
				{
					test: /\.css$/,
					use: [
						/**
						 * MiniCssExtractPlugin doesn't support HMR.
						 * For developing, use 'style-loader' instead.
						 * */
						prod ? MiniCssExtractPlugin.loader : 'style-loader',
						'css-loader'
					]
				},
				{
					test: /\.(png|jpg|gif)$/,
					use: [
						{
							loader: 'file-loader',
							options: {},
						},
					],
				}
			]
		},
		mode,
		plugins: [
			new MiniCssExtractPlugin({
				filename: '[name].css'
			})
		],
		devtool: 'cheap-module-eval-source-map'
		// devtool: prod ? false: 'source-map'
	}; `

this is my svelte file

`	

          <script>

	</script>

	<div class="text">Goodnight moon</div>

	<style type="text/scss" lang="scss">
	@import 'assets/styles/test';
		$color: red;
		h1 {
			color: purple;
			color: $color;
		}
	</style>
`

and the test file 

`

	/// <reference types="cypress" />
	import App from '../../src/App.svelte';
	import mount from 'cypress-svelte-unit-test';

	describe('App component', () => {
	  beforeEach(() => {
		  mount(App)
	  })

	  it('contains a div that has "goodnight moon"', () => {
	    cy.contains('div', 'Goodnight moon');
	  })
	})`

**Comment by JohnnyFun** [comment]
In my case (and probably yours too), I needed to configure cypress to use my system's version of node to run plugins. So in `cypress.json`:

```
"nodeVersion": "system",
```

You might also want to configure svelte to not emit css to global. 

And if you're extracting styles to a css file, just pass the contents of that into the `mount` function. In my case, I setup a cypress task to read the file contents of my built css file:

In index.js (where you configure `@cypress/webpack-preprocessor`), something like:

```
const cssDir = './wwwroot/css'
const cssFile = fs.readdirSync(cssDir).find(f => /main/.test(f))
const appcss = fs.readFileSync(path.join(cssDir, cssFile), 'utf8')
...
module.exports = (on, config) => {
  on('task', {
    getAppCss() { return appcss }
  })
}

And then where you mount your component with `cypress-svelte-unit-test`:
```
import mount from 'cypress-svelte-unit-test'
...
cy.task('getAppCss').then(style => mount(wrapper, { props }, { style }))
```

**Comment by bahmutov** [comment]
Another example https://daveceddia.com/svelte-with-sass-in-vscode/
