### ISSUE TITLE
Why anything Svelte-specific needed for E2E?

### ISSUE THREAD

**Issue by mvolkmann** [bahmutov/cypress-svelte-unit-test#48]
Sorry to open an issue for this since it is really a question.

Are there reasons why we can't write plain Cypress tests to perform end-to-end testing of a Svelte app? Why does Cypress need to do anything special for these assuming that we have "npm run dev" running so there is a server available to serve the app?

**Comment by JohnnyFun** [comment]
It's quicker and isolated. So if you really just want to thoroughly test a single component, this is perfect--no need to load your entire app, which might have lots of js, css, network requests, etc.
