### ISSUE TITLE
Setup instructions unclear for those new to Cypress

### ISSUE THREAD

**Issue by Smona** [bahmutov/cypress-svelte-unit-test#49]
## Is this a bug report or a feature request?

bug report

If this is a bug report, please provide as much info as possible

- version
    "cypress-svelte-unit-test": "^1.5.0"
    "@cypress/webpack-preprocessor": "^4.1.0"
- platform
    macOS (should be platform-independent)
- expected behavior
    The package is able to load webpack configuration when using Sapper. Sapper is a popular project which is closely tied to the svelte ecosystem
- actual behavior
    Running a test which imports a svelte component produces the following error:
```
<project root>/cypress/integration/ContextMenu/example.svelte:1
<ContextMenu>
^
ParseError: Unexpected token
```

Because Sapper uses multiple webpack configurations which are each properties of module.exports, I believe this is because the webpack configuration can't be picked up properly by `svelte-unit-test`. It would be great if this package supported sapper out of the box, but at minimum it should be allowed to customize the webpack file used.

**Comment by bahmutov** [comment]
Absolutely - do you know what it would take and mind opening a pull request?

**Comment by Smona** [comment]
It turns out the plugin is fine and I simply misunderstood the setup instructions. submitted a PR suggesting a more beginner-friendly README
