### ISSUE TITLE
Support for externalized css

### ISSUE THREAD

**Issue by dschulten** [bahmutov/cypress-svelte-unit-test#5]
Feature:
Currently only styles attached to head are supported. A boilerplate app downloaded from the svelte repl writes the component css to a separate file, that is also the recommended way to handle them.
Find a way to determine the location of the css file in a way that works for multiple preprocessors, not just webpack, and include them when mounting the component; also allow for additional global css files. Maybe have a parameter styles on the mount function with an array of css stylesheet urls to link into the page?

**Comment by bahmutov** [comment]
Yup this is common problem for all cypress adaptors and needs to be solved somehow

**Comment by darthmall** [comment]
So this is maybe not ideal, but it's working for me at least as an interim solution.

```javascript
beforeEach(() => {
  cy.document().then(doc => {
    const style = doc.createElement('link')

    style.rel = 'stylesheet'
    style.type = 'text/css'
    style.href = '/global.css'

    doc.querySelector('head').appendChild(style)
  })

  mount(MyComponent)
})
```

This requires me to have my dev server running at the `baseUrl` configured for Cypress so that `global.css` can be loaded.

**Comment by JohnnyFun** [comment]
I exposed my extracted global css with a cypress task for components that require it. This doesn't require your dev server be running, but it does require that your css is built.

So in index.js (where you define your webpack config for cypress)
```
const cssDir = './wwwroot/css'
const cssFile = fs.readdirSync(cssDir).find(f => /main/.test(f))
const appcss = fs.readFileSync(path.join(cssDir, cssFile), 'utf8')
....
// https://docs.cypress.io/api/commands/task.html#Syntax
on('task', {
  getAppCss() { return appcss }
})
```

Then, I have a helper function like:
```
import mount from 'cypress-svelte-unit-test'
export default function mountCustom(component, props, needsAppCss = false) {
  if (needsAppCss)
    cy.task('getAppCss').then(style => mount(component, { props }, { style }))
  else
    mount(component, { props })
}
```

**Comment by bahmutov** [comment]
@dschulten I am not sure what you are describing. Can you be as specific as possible, hopefully with a simple and concise example code?
