### ISSUE TITLE
No CSS styling 

### ISSUE THREAD

**Issue by JeffWScott** [bahmutov/cypress-svelte-unit-test#52]
"cypress": "^3.4.1","
@cypress/webpack-preprocessor": "^4.1.0",

I have everything else working okay, it's just when I view the videos or web interface I have no CSS styling.   My app uses a combination of in component styling and a #global.css file.  Did I miss a step somewhere?  The app works and looks great on a regular build.

**Comment by JohnnyFun** [comment]
You may need to configure cypress to use the version of node your system uses. See this for more info: https://github.com/bahmutov/cypress-svelte-unit-test/issues/45

**Comment by wyozi** [comment]
Rollup template that comes with svelte template contains lines to generate external CSS (https://github.com/sveltejs/template/blob/master/rollup.config.js#L23-L25). Commenting those out in testing mode fixed styles for me

**Comment by bahmutov** [comment]
@wyozi could you open a separate issue for this with a link to the repo? I was thinking of cleaning up rollup config automatically when loading it for tests, but without a good reason did not want to do it
