### ISSUE TITLE
Using With Rollup

### ISSUE THREAD

**Issue by remieyu** [bahmutov/cypress-svelte-unit-test#53]
Is it possible to use this with Rollup instead of Webpack?

**Comment by JohnnyFun** [comment]
Did you try https://github.com/dschulten/cypress-rollup-preprocessor? More docs on configuring cypress plugin preprocessors here: https://docs.cypress.io/api/plugins/preprocessors-api.html#Usage

**Comment by bahmutov** [comment]
Trying to plug in https://github.com/bahmutov/cy-rollup
