### ISSUE TITLE
Can we collect code coverage?

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-svelte-unit-test#70]
That would be very nice

**Comment by alejandroiglesias** [comment]
I implemented the coverage as instructed but it seems to work for the template and not for the code in the `<script>` tags. It may be related to [this issue](https://github.com/sveltejs/svelte/issues/286). Is there any way to have coverage for the full component code that is not documented in the README of this project? I'm using `@bahmutov/cy-rollup` as instructed in the README. Thanks in advance.
