### ISSUE TITLE
Allow to use api of mounted component

### ISSUE THREAD

**Issue by dschulten** [bahmutov/cypress-svelte-unit-test#9]
Feature:
A Svelte component's api should be made accessible to the test. A test may want to call ˋon()ˋ to listen for events fired by the component, it may want to call ˋobserve()ˋ to be notified of changes in the data, or it may simply need to call one of the ˋmethodsˋ in the component.
It might be sufficient to return the component instance after it has been created to resolve the promise.

**Comment by dschulten** [comment]
Closing. Cypress.component holds the component when the mount promise is being resolved:

```
mount(InputText, this.data).then((foo) =>
			// console.log(foo)
			Cypress.component.observe('value', (val) =>
				console.log(val)
			)
		);
```

**Comment by JohnnyFun** [comment]
Also, fwiw, to call `$set` on the cypress component, this works:

```
// make a "set" function
Cypress.component.set = props => cy.wrap({ do: () => Cypress.component.$set(props) }).invoke('do')
...
Cypress.component.set({ value: 'updated!' })
```

There may be a more elegant way, but this works great.

**Comment by alejandroiglesias** [comment]
@JohnnyFun I couldn't make your solution work. Can you elaborate? Do you add the `set` method in the 
`commands.js` file?

**Comment by JohnnyFun** [comment]
Yeah, the api has changed since then. I made a function that wraps the mount method like:

```

import { mount } from 'cypress-svelte-unit-test' // './temp-cypress-svelte-unit-test'
import wrapper from 'fixtures/components/wrapper'

export default function mountCustom(component, props) {
  const options = { props: { component, props } }
  const returnComponent = c => {
    // so you can set props on a mounted component
    c.set = delta => {
      cy.wrap({
        setDelta: () => {
          const newProps = {
            c,
            props: { ...props, ...delta },
          }
          c.$set(newProps)
        },
      }).invoke('setDelta')
    }
    return c
  }
  return mount(wrapper, options).then(returnComponent)
}
```

Then it can be used like:

```
import mount from 'support/customMount'
import MyComponent from 'components/MyComponent'

describe('myComponent', () => {
  it('does stuff', () => {
    mount(MyComponent, { value: 'initial' }).then(component => {
       // ....
      component.set('changed value') // yar
    })
  })
})
```
